### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by virux99** [mikescandy/FilePicker#1]
on main layout, getting null reference, cant access the files and folders.

**Comment by mikescandy** [comment]
Just tried and it seems to work here. Could you provide more details? (device, android version, stacktrace, anything really : ) )

**Comment by virux99** [comment]
sorry bro, didn't give permission to access the file. my bad :)
thanks for respoce.

**Comment by mikescandy** [comment]
can I close?

**Comment by virux99** [comment]
yup
